# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-09 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=25)),
                ('classe', models.CharField(max_length=15)),
                ('genie', models.CharField(max_length=15)),
                ('matiere', models.CharField(max_length=15)),
                ('objet', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiants',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=25)),
                ('prenom', models.CharField(max_length=30)),
                ('classe', models.CharField(max_length=15)),
                ('genie', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to=b'')),
                ('genre', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ESPACE_ETUDIANTS.Documents')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ESPACE_ETUDIANTS.Etudiants')),
            ],
        ),
        migrations.AddField(
            model_name='consultations',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ESPACE_ETUDIANTS.Documents'),
        ),
        migrations.AddField(
            model_name='consultations',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ESPACE_ETUDIANTS.Etudiants'),
        ),
    ]
